server.port=${PORT:8004}
spring.datasource.url=jdbc:mysql://${DB_HOST:mysql}:3306/cities?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:shipping}
spring.datasource.password=${DB_PASS:RoboShop@1}
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true
